services:
  postgres:
    image: postgres:16
    container_name: hotel_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: hotel_db
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - hotel_postgres_data:/var/lib/postgresql/data

volumes:
  hotel_postgres_data: