services:
  postgres:
    image: postgres:16
    container_name: hotel_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: hotel_db
      POSTGRES_USER: ${DB_USER}  # ← .env
      POSTGRES_PASSWORD: ${DB_PASSWORD}  # ← .env
    ports:
      - "5433:5432"
    volumes:
      - hotel_postgres_data:/var/lib/postgresql/data
    networks:
      - hotel_network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hotel_backend
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/hotel_db # ← dev
      SPRING_DATASOURCE_USERNAME: ${DB_USER}  # ← .env
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD} # ← .env
      JWT_SECRET: ${JWT_SECRET}
      SPRING_CONFIG_IMPORT: optional:file:./env/
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - hotel_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}  # ← agrega esto
    container_name: hotel_frontend
    restart: unless-stopped
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - hotel_network

networks:
  hotel_network:
    driver: bridge

volumes:
  hotel_postgres_data: