jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

spring:
  datasource:
    username: ${DB_USER}
    password: ${DB_PASSWORD}

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    try-it-out-enabled: true       # Habilita el botón "Try it out"
    operations-sorter: method      # Ordena endpoints por método HTTP
    tags-sorter: alpha             # Ordena los tags alfabéticamente
    display-request-duration: true # Muestra el tiempo de respuesta
  packages-to-scan: com.richglez.hotel  # Escanea solo ese paquete

# le dice a Spring cómo conectarse a la DB