name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # ─────────────────────────────────────────
  # JOB 1: Tests backend (Spring Boot)
  # ─────────────────────────────────────────
  backend-ci: # ID JOB
    name: Backend — Build & Test
    runs-on: ubuntu-latest

    services: # create a container in VM
      postgres: # service name (database test/temp)
        image: postgres:16    # levanta un contenedor de postgres igual que docker-compose
        env: # credenciales de la base temporal
          POSTGRES_DB: hotel_test # base de datos para tests
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        # postgres listo ? si/no
        # pregunta cada 10 s si esta listo
        # si en 5 segundos no responde -> failed
        # si falla 5 veces seguidas -> algo salio mal

    steps:  # Job Step
      - name: Checkout code
        uses: actions/checkout@v6   # Accion / Funcion de clonar repositorio en la VM

      - name: Setup Java 21 VM
        uses: actions/setup-java@v5  # Accion / Funcion de instalar java en VM
        with:  # Pasar parametros y variables a la accion de arriba
          java-version: '21'  # Same as project
          distribution: 'temurin'  # Distribucion de java
          cache: 'maven' # Guarda las dependencias entre runs

      - name: Give permission to mvnw
        run: chmod +x ./mvnw    # Agregale permiso de ejecucion 'x' a este archivo

      - name: Run tests
        run: ./mvnw verify
        env:    # Create env file in VM
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/hotel_test
          SPRING_DATASOURCE_USERNAME: postgres
          SPRING_DATASOURCE_PASSWORD: postgres
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
